version: '3.8'

services:
  google-adk-chat:
    build: .
    container_name: google-adk-chat
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # 大模型配置
      - LLM_BASE_URL=https://api.openai.com/v1
      - LLM_MODEL=gpt-3.5-turbo
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_TEMPERATURE=0.7
      - LLM_MAX_TOKENS=2048
      - LLM_TIMEOUT=30
      
      # Web服务器配置
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8000
      - DEBUG_MODE=false
      
      # 日志配置
      - LOG_LEVEL=INFO
      - LOG_FILE=logs/app.log
      
      # MCP工具目录
      - MCP_TOOLS_DIR=src/mcp_tools
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro  # 只读挂载环境文件
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - google-adk-network

  # 可选：Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: google-adk-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - google-adk-network
    profiles:
      - with-redis

  # 可选：Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: google-adk-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - google-adk-chat
    networks:
      - google-adk-network
    profiles:
      - with-nginx

networks:
  google-adk-network:
    driver: bridge

volumes:
  redis_data:
    driver: local